CREATE TABLE IF NOT EXISTS "users"
(
    "user_id"  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email"    varchar(33) NOT NULL,
    "login"    varchar(20) NOT NULL,
    "username" varchar(20),
    "birthday" date
);

CREATE TABLE IF NOT EXISTS "friends"
(
    "user_id"              bigint NOT NULL,
    "friend_id"            bigint NOT NULL,
    "friendship_status_id" int NOT NULL,
    PRIMARY KEY ("user_id", "friend_id")
);

CREATE TABLE IF NOT EXISTS "friendship_status"
(
    "friendship_status_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "status" varchar(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS "films"
(
    "film_id"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"         varchar(50)  NOT NULL,
    "description" varchar(200) NOT NULL,
    "release_date" date         NOT NULL,
    "duration"     int          NOT NULL,
    "mpa_id"       int          NOT NULL
);

CREATE TABLE IF NOT EXISTS "mpas"
(
    "mpa_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mpa" varchar(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS "likes"
(
    "film_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    PRIMARY KEY ("film_id", "user_id")
);

CREATE TABLE IF NOT EXISTS "films_genre"
(
    "film_id"  bigint NOT NULL,
    "genre_id" int    NOT NULL,
    PRIMARY KEY ("film_id", "genre_id")
);

CREATE TABLE IF NOT EXISTS "genres"
(
    "genre_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "genre" varchar(33) NOT NULL
);

ALTER TABLE "friends"
    ADD FOREIGN KEY ("friendship_status_id") REFERENCES "friendship_status" ("friendship_status_id");

ALTER TABLE "friends"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "friends"
    ADD FOREIGN KEY ("friend_id") REFERENCES "users" ("user_id");

ALTER TABLE "films"
    ADD FOREIGN KEY ("mpa_id") REFERENCES "mpas" ("mpa_id");

ALTER TABLE "likes"
    ADD FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");

ALTER TABLE "likes"
    ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "films_genre"
    ADD FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");

ALTER TABLE "films_genre"
    ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("genre_id");